export const movies = [
    {
        id: 'mc-movie-1' ,
        title: 'Mindcage',
        synopsis: 'Two homicide detectives reluctantly consult an imprisoned serial killer whose diabolical mind holds the key to a series of baffling copycat murders.',
        thumbnailUrl: 'movies/tn/1.webp',
        posterUrl: 'movies/posters/1.webp',
        year:"2022",
        duration: "1h36min",
        director:"Mauro Borrelli",
        starring: ["Martin Lawrence", "Melissa Roxburgh", "John Malkovich"],
        fiveStarRating: 3,
        trailerURL:"https://www.youtube.com/watch?v=7d8XdU8cb18",
        matchPercent: '62',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'legal drugs']
        },
        genres: ['Thriller', 'Mystery', 'Psychological'],
    },
    {
        id: 're-movie-1' ,
        title: 'Red Eye',
        synopsis: 'On an overnight flight to Miami, an emotionally raw hotel manager finds herself ensnared in a menacing passenger\'s political assassination plot.',
        thumbnailUrl: 'movies/tn/2.webp',
        posterUrl: 'movies/posters/2.webp',
        year: "2005",
        trailerURL:"https://youtube.com/watch?v=GoXQZyNpeIk",
        matchPercent: '60',
        duration: "1h26min",
        director:"Wes Craven",
        starring: ["Rachel McAdams", "Cillian Murphy", "Brian Cox"],
        fiveStarRating: 1,
        pg:{
            age: 14,
            content: ['violence']
        },
        genres: ['Thriller', 'Suspense', 'Psychological'],
    },
    {
        id: 'gg-movie-1' ,
        title: 'Gerald\'s Game',
        synopsis: 'When her husband\'s sex game goes wrong, Jessie -- handcuffed to a bed in a remote lake house -- faces warped visions, dark secrets and a dire choice.',
        thumbnailUrl: 'movies/tn/3.jpg',
        year: "2017",
        trailerURL:"https://www.youtube.com/watch?v=twbGU2CqqQU",
        posterUrl: 'movies/posters/3.webp',
        matchPercent: '60',
        duration: "1h43min",
        director:"Mike Flanagan",
        starring: ["Carla Gugino", "Bruce Greenwood", "Henry Thomas"],
        fiveStarRating: 1,
        pg:{
            age: 16,
            content: ['violence', 'fear', 'inappropriate language']
        },
        genres: ['Thriller', 'Horror', 'Based on Books'],
    },
    {
        id: 'tbc-movie-1' ,
        title: 'The Bone Collector',
        synopsis: 'A rookie cop reluctantly teams with a paralyzed ex-detective to catch a grisly serial killer dubbed the Bone Collector in this crime thriller.',
        thumbnailUrl: 'movies/tn/4.webp',
        year: "1999",
        trailerURL:"https://www.youtube.com/watch?v=w4z4Xsp-bos",
        posterUrl: 'movies/posters/4.webp',
        matchPercent: '59',
        duration: "1h57min",
        director:"Phillip Noyce",
        starring: ["Denzel Washington", "Angelina Jolie", "Queen Latifah"],
        fiveStarRating: 1,
        pg:{
            age: 14,
            content: ['violence']
        },
        genres: ['Thriller', 'Drama', 'Mystery'],
    },
    {
        id: 'gcl-movie-1' ,
        title: 'God\'s Crooked Lines',
        synopsis: 'A private detective who claims to be suffering from paranoia checks into a psychiatric hospital to investigate another patient\'s mysterious death.',
        thumbnailUrl: 'movies/tn/5.jpg',
        year: "2022",
        trailerURL:"https://www.youtube.com/watch?v=gEdTzJ6UPeA",
        posterUrl: 'movies/posters/5.webp',
        matchPercent: '59',
        duration: "2h35min",
        director:"Oriol Paulo",
        starring: ["Bárbara Lennie", "Eduard Fernandez", "Loreto Mauleon"],
        fiveStarRating: 1,
        pg:{
            age: 14,
            content: ['violence', 'legal drugs', 'nudity']
        },
        genres: ['Thriller', 'Drama', 'Spanish'],
    },
    {
        id: 'nysm-movie-1' ,
        title: 'Now You See Me',
        synopsis: 'A troupe of brainy illusionists specialize in stealing from banks and giving the cash to their audiences, all while outwitting a team of FBI agents.',
        thumbnailUrl: 'movies/tn/6.webp',
        year: "2013",
        trailerURL:"https://www.youtube.com/watch?v=KzJNYYkkhzc",
        posterUrl: 'movies/posters/6.webp',
        matchPercent: '59',
        duration: "1h55min",
        director:"Louis Leterrier",
        starring: ["Jesse Eisenberg", "Mark Ruffalo", "Isla Fisher"],
        fiveStarRating: 1,
        pg:{
            age: 12,
            content: ['violence']
        },
        genres: ['Thriller', 'Mystery', 'Suspense'],
    },
    {
        id: 'twitw-movie-1' ,
        title: 'The Woman In the Window',
        synopsis: 'Confined to her home by agoraphobia, a psychologist becomes obsessed with her new neighbors — and solving a brutal crime she witnesses from her window.',
        thumbnailUrl: 'movies/tn/7.jpg',
        year: "2021",
        trailerURL: "https://www.youtube.com/watch?v=v_0GJg_Jnlo",
        posterUrl: 'movies/posters/7.webp',
        matchPercent: '58',
        duration: "1h41min",
        director:"Joe Wright",
        starring: ["Amy Adams", "Gary Oldman", "Anthony Mackie"],
        fiveStarRating: 1,
        pg:{
            age: 16,
            content: ['violence', 'legal drugs', 'inappropriate language']
        },
        genres: ['Thriller', 'Mystery', 'Drama'],
    },
    {
        id: 'iam-movie-1' ,
        title: 'I Am Mother',
        synopsis: 'Following humanity\'s mass extinction, a teen raised alone by a maternal droid finds her entire world shaken when she encounters another human.',
        thumbnailUrl: 'movies/tn/8.jpg',
        year: "2021",
        trailerURL: "https://www.youtube.com/watch?v=v_0GJg_Jnlo",
        posterUrl: 'movies/posters/8.webp',
        matchPercent: '57',
        duration: "1h53min",
        director:"Grant Sputore",
        starring: ["Clara Rugaard", "Rose Byrne", "Hilary Swank"],
        fiveStarRating: 1,
        pg:{
            age: 12,
            content: ['violence', 'inappropriate language']
        },
        genres: ['Thriller', 'Sci-Fi', 'Australian'],
    },
    {
        id: 'nw-movie-1' ,
        title: 'Nowhere',
        synopsis: 'Pregnant, alone and drifting in the sea, a woman trapped in a shipping container tries to survive after fleeing a devastated totalitarian country.',
        thumbnailUrl: 'movies/tn/9.jpg',
        year: "2023",
        trailerURL: "https://www.youtube.com/watch?v=KDUtdcU10YA",
        posterUrl: 'movies/posters/9.webp',
        matchPercent: '56',
        duration: "1h49min",
        director:"Albert Pinto",
        starring: ["Anna Castillo", "Tamar Novas", "Tony Corvillo"],
        fiveStarRating: 1,
        pg:{
            age: 16,
            content: ['violence']
        },
        genres: ['Thriller', 'Drama', 'Spanish'],
    },
    {
        id: 'tg-movie-1' ,
        title: 'The Game',
        synopsis: 'An aloof investment banker\'s life spirals into peril and paranoia after his brother gives him an odd birthday gift: the chance to play a mysterious game.',
        thumbnailUrl: 'movies/tn/10.webp',
        year: "1997",
        trailerURL: "https://www.youtube.com/watch?v=nsKdR05ZsGE",
        posterUrl: 'movies/posters/10.webp',
        matchPercent: '55',
        duration: "2h8min",
        director:"David Fincher",
        starring: ["Michael Douglas", "Sean Penn", "Deborah Kara Unger"],
        fiveStarRating: 1,
        pg:{
            age: 12,
            content: ['violence']
        },
        genres: ['Thriller', 'Mystery', 'Film Noir'],
    },
    {
        id: 'r-movie-1' ,
        title: 'Replicas',
        synopsis: 'After losing his family in a tragic accident, a neuroscientist tries to bring them back in a cloning experiment that attracts controversy and chaos.',
        thumbnailUrl: 'movies/tn/11.webp',
        year: "2018",
        trailerURL: "https://www.youtube.com/watch?v=bKdpGHazAqs",
        posterUrl:  'movies/posters/11.webp',
        matchPercent: '55',
        duration: "1h47min",
        director:"Jeffrey Nachmannoff",
        starring: ["Keanu Reeves", "Alice Eve", "Thomas Middleditch"],
        fiveStarRating: 1,
        pg:{
            age: 14,
            content: ['violence']
        },
        genres: ['Thriller', 'Sci-Fi', 'Suspense'],
    },
    {
        id: 'itsotm-movie-1' ,
        title: 'In The Shadow Of The Moon',
        synopsis: 'A Philadelphia detective slowly unravels as he nurses a lifelong obsession with an enigmatic female serial killer whose crimes defy explanation.',
        thumbnailUrl: 'movies/tn/12.jpg',
        year: "2019",
        trailerURL: "https://www.youtube.com/watch?v=lJ3_biTbeRM",
        posterUrl: 'movies/posters/12.webp',
        matchPercent: '55',
        duration: "1h55min",
        director:"Jim Mickle",
        starring: ["Boyd Holbrook", "Michael C. Hall", "Cleopatra Coleman"],
        fiveStarRating: 1,
        pg:{
            age: 14,
            content: ['violence', 'illegal drugs', 'inappropriate language']
        },
        genres: ['Thriller', 'Sci-Fi', 'Drama'],
    },
]