export const tvShows = [
    {
        id: 'tb-tvshow-1' ,
        title: 'The Blacklist',
        synopsis: 'After turning himself in, a brilliant fugitive offers to help the FBI bag other baddies, but only if rookie profiler Elizabeth Keen is his partner.',
        thumbnailUrl: 'tv-shows/tn/1.webp',
        year: "2023",
        trailerURL: "https://www.youtube.com/watch?v=SGB5cMf0r4I",
        seasons: "10",
        director:"Jon Bokenkamp",
        starring: ["James Spader", "Megan Boone", "Diego Klattenhoff"],
        posterUrl: 'tv-shows/posters/1.webp',
        matchPercent: '98',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'drugs']
        },
        genres: ['Drama', 'Crime', 'Psychological'],
    },
    {
        id: 'bb-tvshow-1' ,
        title: 'Breaking Bad',
        synopsis: 'Diagnosed with terminal lung cancer, a high school chemistry teacher resorts to cooking and selling methamphetamine to provide for his family.',
        thumbnailUrl: 'tv-shows/tn/2.webp',
        year: "2013",
        trailerURL: "https://www.youtube.com/watch?v=HhesaQXLuRY",
        seasons: "5",
        director:"Vince Gilligan",
        starring: ["Bryan Cranston", "Aaron Paul", "Anna Gunn"],
        posterUrl: 'tv-shows/posters/2.webp',
        matchPercent: '98',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'illegal drugs']
        },
        genres: ['Drama', 'Thriller', 'US TV Shows'],
    },
    {
        id: 'thohh-tvshow-1' ,
        title: 'The Haunting Of Hill House',
        synopsis: 'While investigating a ghost story for his latest novel, a skeptical Steven receives a call from his sister that triggers a chain of fateful events.',
        thumbnailUrl: 'tv-shows/tn/3.jpg',
        year: "2018",
        trailerURL: "https://www.youtube.com/watch?v=VxEEGi9V0kI",
        seasons: "1",
        director:"Mike Flanagan",
        starring: ["Michiel Huisman", "Carla Gugino", "Timothy Hutton"],
        posterUrl: 'tv-shows/posters/3.webp',
        matchPercent: '98',
        pg:{
            age: 16,
            content: ['sensitive themes', 'inappropriate language', 'illegal drugs']
        },
        genres: ['Drama', 'Mystery', 'Based on Books'],
    },
    {
        id: 'twd-tvshow-1' ,
        title: 'The Walking Dead',
        synopsis: 'Rick goes back to Atlanta to retrieve the bag of guns and save a man\'s life. Lori and Shane deal with the return of someone they thought was dead.',
        thumbnailUrl: 'tv-shows/tn/4.webp',
        year: "2021",
        trailerURL: "https://www.youtube.com/watch?v=sfAc2U20uyg",
        seasons: "11",
        director:"",
        starring: ["Andrew Lincoln", "Steven Yeun", "Norman Reedus"],
        posterUrl:  'tv-shows/posters/4.webp',
        matchPercent: '97',
        pg:{
            age: 18,
            content: ['extreme violence', 'fear']
        },
        genres: ['Drama', 'Action', 'US TV Shows'],
    },
    {
        id: 'mh-tvshow-1' ,
        title: 'Mindhunter',
        synopsis: 'In the late 1970s two FBI agents expand criminal science by delving into the psychology of murder and getting uneasily close to all-too-real monsters.',
        thumbnailUrl: 'tv-shows/tn/5.jpg',
        year: "2019",
        trailerURL: "https://www.youtube.com/watch?v=DHJO6VR6TYY",
        seasons: "2",
        director:"Joe Penhall",
        starring: ["Jonathan Groff", "Holt McCallany", "Anna Torv"],
        posterUrl: 'tv-shows/posters/5.webp',
        matchPercent: '96',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'drugs']
        },
        genres: ['Drama', 'Mystery', 'Based on Books'],
    },
    {
        id: 'bcs-tvshow-1' ,
        title: 'Better Call Saul',
        synopsis: 'This Emmy-nominated prequel to "Breaking Bad" follows small-time attorney Jimmy McGill as he transforms into morally challenged lawyer Saul Goodman.',
        thumbnailUrl: 'tv-shows/tn/6.jpg',
        year: "2022",
        trailerURL: "https://www.youtube.com/watch?v=HN4oydykJFc",
        seasons: "6",
        director:"Vince Gilligan",
        starring: ["Bob Odenkirk", "Jonathan Banks", "Rhea Seehorn"],
        posterUrl: 'tv-shows/posters/6.webp',
        matchPercent: '96',
        pg:{
            age: 16,
            content: ['violence', 'illegal drugs']
        },
        genres: ['Drama', 'US TV Shows'],
    },
    {
        id: 'th-tvshow-1' ,
        title: 'The 100',
        synopsis: 'A century after Earth was devastated by a nuclear apocalypse, 100 space station residents are sent to the planet to determine whether it\'s habitable.',
        thumbnailUrl: 'tv-shows/tn/7.webp',
        year: "2020",
        trailerURL: "https://www.youtube.com/watch?v=aDrsItJ_HU4",
        seasons: "7",
        director:"Jason Rothenberg",
        starring: ["Eliza Taylor", "Paige Turco", "Bob Morley"],
        posterUrl: 'tv-shows/posters/7.webp',
        matchPercent: '95',
        pg:{
            age: 16,
            content: ['violence', 'sensitive themes']
        },
        genres: ['Drama', 'Sci-Fi', 'Political'],
    },
    {
        id: 'o-tvshow-1' ,
        title: 'Ozark',
        synopsis: 'A financial adviser drags his family from Chicago to the Missouri Ozarks, where he must launder $500 million in five years to appease a drug boss.',
        thumbnailUrl: 'tv-shows/tn/8.jpg',
        year: "2022",
        trailerURL: "https://www.youtube.com/watch?v=5hAXVqrljbs",
        seasons: "4",
        director:"Bill Dubuque",
        starring: ["Jason Bateman", "Laura Linney", "Sofia Hublitz"],
        posterUrl: 'tv-shows/posters/8.webp',
        matchPercent: '94',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'illegal drugs']
        },
        genres: ['Drama', 'Thriller', 'US TV Shows'],
    },
    {
        id: 'toa-tvshow-1' ,
        title: 'The OA',
        synopsis: 'Seven years after vanishing from her home, a young woman returns with mysterious new abilities and recruits five strangers for a secret mission.',
        thumbnailUrl: 'tv-shows/tn/9.jpg',
        year: "2019",
        trailerURL: "https://www.youtube.com/watch?v=DvHJtez2IlY",
        seasons: "2",
        director:"Brit Marling",
        starring: ["Brit Marling", "Jason Isaacs", "Emory Cohen"],
        posterUrl: 'tv-shows/posters/9.webp',
        matchPercent: '84',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'drugs']
        },
        genres: ['Drama', 'Sci-Fi', 'Mystery'],
    },
    {
        id: 'tfothou-tvshow-1' ,
        title: 'The Fall Of The House Of Usher',
        synopsis: 'To secure their fortune — and future — two ruthless siblings build a family dynasty that begins to crumble when their heirs mysteriously die, one by one.',
        thumbnailUrl: 'tv-shows/tn/10.jpg',
        year: "2023",
        trailerURL: "https://www.youtube.com/watch?v=yvuAWVzP6wI",
        seasons: "1",
        director:"Mike Flanagan",
        starring: ["Carla Gugino", "Bruce Greenwood", "Mary McDonnell"],
        posterUrl: 'tv-shows/posters/10.webp',
        matchPercent: '94',
        pg:{
            age: 16,
            content: ['extreme violence', 'sexual content', 'illegal drugs']
        },
        genres: ['Drama', 'Based on Books', 'US TV Shows'],
    },
    {
        id: 'dmtjds-tvshow-1' ,
        title: 'Dahmer - Monster: The Jeffrey Dahmer Story',
        synopsis: 'Across more than a decade, 17 teen boys and young men were murdered by convicted killer Jeffrey Dahmer. How did he evade arrest for so long?',
        thumbnailUrl: 'tv-shows/tn/11.jpg',
        year: "2022",
        trailerURL: "https://www.youtube.com/watch?v=81H-zzjm0-I",
        seasons: "1",
        director:"Ryan Murphy",
        starring: ["Evan Peters", "Richard Jenkins", "Niecy Nash-Betts"],
        posterUrl:  'tv-shows/posters/11.webp',
        matchPercent: '93',
        pg:{
            age: 18,
            content: ['extreme violence', 'explicit sex', 'drugs']
        },
        genres: ['Drama', 'Horror', 'US TV Shows'],
    },
    {
        id: 'luci-tvshow-1' ,
        title: 'Lucifer',
        synopsis: 'Bored with being the Lord of Hell, the devil relocates to Los Angeles, where he opens a nightclub and forms a connection with a homicide detective.',
        thumbnailUrl: 'tv-shows/tn/12.jpg',
        year: "2021",
        trailerURL: "https://www.youtube.com/watch?v=X4bF_quwNtw",
        seasons: "6",
        director:"",
        starring: ["Tom Ellis", "Lauren German", "Kevin Alejandro"],
        posterUrl: 'tv-shows/posters/12.webp',
        matchPercent: '89',
        pg:{
            age: 14,
            content: ['illegal drugs']
        },
        genres: ['Drama', 'Crime', 'US TV Shows'],
    },
    {
        id: 'hmd-tvshow-1' ,
        title: 'House M.D.',
        synopsis: 'Hugh Laurie stars as Dr. Gregory House, an ornery physician who loathes his patients but is a genius at treating mysterious ailments.',
        thumbnailUrl: 'tv-shows/tn/14.webp',
        year: "2011",
        trailerURL: "https://www.youtube.com/watch?v=MczMB8nU1sY",
        seasons: "8",
        director:"David Shore",
        starring: ["Hugh Laurie", "Omar Epps", "Robert Sean Leonard"],
        posterUrl: 'tv-shows/posters/14.webp',
        matchPercent: '92',
        pg:{
            age: 16,
            content: ['illegal drugs', 'medical procedures']
        },
        genres: ['Drama', 'Medical', 'US TV Shows'],
    },
    {
        id: 'tmc-tvshow-1' ,
        title: 'The Midnight Club',
        synopsis: 'Inside a hospice for terminally ill teens, members of an exclusive club make a chilling pact: The first to die must send a sign from beyond the grave.',
        thumbnailUrl: 'tv-shows/tn/15.jpg',
        year: "2022",
        trailerURL: "https://www.youtube.com/watch?v=lBhyUxRzANY",
        seasons: "10",
        director:"Leah Fong",
        starring: ["Iman Benson", "Igby Rigney", "Ruth Codd"],
        posterUrl:  'tv-shows/posters/15.webp',
        matchPercent: '89',
        pg:{
            age: 16,
            content: ['violence', 'inappropriate language', 'illegal drugs']
        },
        genres: ['Drama', 'Teen', 'Based on Books'],
    },
    {
        id: 's-tvshow-1' ,
        title: 'Suits',
        synopsis: 'After impressing a slick lawyer with his razor-sharp mind, a college dropout scores a coveted associate job, even though he has no legal credentials.',
        thumbnailUrl: 'tv-shows/tn/16.webp',
        year: "2019",
        trailerURL: "https://www.youtube.com/watch?v=Ab2YIbP5xw8",
        seasons: "9",
        director:"Aaron Korsh",
        starring: ["Gabriel Macht", "Patrick J. Adams", "Sarah Rafferty"],
        posterUrl: 'tv-shows/posters/16.webp',
        matchPercent: '90',
        pg:{
            age: 14,
            content: ['violence', 'sexual content', 'drugs']
        },
        genres: ['Drama', 'Courtroom', 'Comedy'],
    },
    {
        id: 'vv-tvshow-1' ,
        title: 'Vikings: Valhalla',
        synopsis: 'In this sequel to "Vikings," a hundred years have passed and a new generation of legendary heroes arises to forge its own destiny — and make history.',
        thumbnailUrl: 'tv-shows/tn/17.jpg',
        year: "2023",
        trailerURL: "https://www.youtube.com/watch?v=Yi4YnwFT7Gk&pp=ygUaVmlraW5nczogVmFsaGFsbGEgXHRyYWlsZXI%3D",
        seasons: "2",
        director:"Niels Arden Oplev",
        starring: ["Sam Corlett", "Leo Suter", "Frida Gustavsson"],
        posterUrl:'tv-shows/posters/17.webp',
        matchPercent: '81',
        pg:{
            age: 16,
            content: ['extreme violence', 'sexual content']
        },
        genres: ['Drama', 'Action', 'Adventure'],
    },
    {
        id: 'ys-tvshow-1' ,
        title: 'Yellowstone',
        synopsis: 'The owner of Montana\'s largest ranch, John Dutton, defends a vanishing way of life as business interests and politicians scheme to force him out.',
        thumbnailUrl: 'tv-shows/tn/19.webp',
        year: "2020",
        trailerURL: "https://www.youtube.com/watch?v=jr32f0rnK1o",
        seasons: "3",
        director:"Taylor Sheridan",
        starring: ["Kevin Costner", "Kelly Reilly", "Luke Grimes"],
        posterUrl: 'tv-shows/posters/19.webp',
        matchPercent: '88',
        pg:{
            age: 16,
            content: ['violence', 'sexual content', 'drugs']
        },
        genres: ['Drama', 'US TV Shows'],
    },
]